# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [1]:
print("H")

H

In [1]:
import pandas as pd
import numpy as np

# Load in the data file using `pd.read_csv()`

In [15]:
# Load data here
data_file = pd.read_csv("data/listings.csv", sep=",")
print(data_file)

             id                                               name    host_id  \
0          2595                              Skylit Midtown Castle       2845
1          3831  Whole flr w/private bdrm, bath & kitchen(pls r...       4869
2          5121                                    BlissArtsSpace!       7356
3          5136           Spacious Brooklyn Duplex, Patio + Garden       7378
4          5178                   Large Furnished Room Near B'way　       8967
...         ...                                                ...        ...
46522  44807522         Designer Gramercy Studio Townhouse by UNSQ   12941925
46523  44807786  Cozy & comfy apt in the heart of Inwood Manhattan  284790520
46524  44811717  Comfortable safe environment 24hr security camera  362453686
46525  44814944                 Upper West Side studio 86th Street    4039777
46526  44818009  5MIN D/N trains, NEAR THE BEACH, 50’ TO MANHATTAN   48098268

         host_name neighbourhood_group       neighbourhood  latitude  \
0         Jennifer           Manhattan             Midtown  40.75362
1      LisaRoxanne            Brooklyn        Clinton Hill  40.68514
2            Garon            Brooklyn  Bedford-Stuyvesant  40.68688
3          Rebecca            Brooklyn         Sunset Park  40.66120
4         Shunichi           Manhattan      Hell's Kitchen  40.76489
...            ...                 ...                 ...       ...
46522        Brian           Manhattan            Gramercy  40.73433
46523        Salar           Manhattan  Washington Heights  40.85820
46524       Nicole            Brooklyn       East Flatbush  40.65399
46525     Fernando           Manhattan     Upper West Side  40.78731
46526       Marina            Brooklyn           Gravesend  40.59945

       longitude        room_type  price  minimum_nights  number_of_reviews  \
0      -73.98377  Entire home/apt    175               3                 48
1      -73.95976  Entire home/apt     75               1                340
2      -73.95596     Private room     60              29                 50
3      -73.99423  Entire home/apt    175              14                  1
4      -73.98493     Private room     65               2                473
...          ...              ...    ...             ...                ...
46522  -73.98383  Entire home/apt    145               7                  0
46523  -73.92733  Entire home/apt     87               6                  0
46524  -73.93287     Private room     59               3                  0
46525  -73.97029  Entire home/apt     80              30                  0
46526  -73.98209     Private room     66               1                  0

      last_review  reviews_per_month  calculated_host_listings_count  \
0      2019-11-04               0.37                               2
1      2020-08-01               4.75                               1
2      2019-12-02               0.37                               1
3      2014-01-02               0.01                               1
4      2020-03-15               3.44                               1
...           ...                ...                             ...
46522         NaN                NaN                               1
46523         NaN                NaN                               2
46524         NaN                NaN                               1
46525         NaN                NaN                               1
46526         NaN                NaN                               1

       availability_365
0                   365
1                   265
2                   365
3                   295
4                   340
...                 ...
46522               164
46523                85
46524                90
46525               113
46526                38

[46527 rows x 16 columns]

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`

In [24]:
# 1. How many listings are there with a price less than 100? 
select_condition = data_file['price'] < 100

listings_under100 = data_file[select_condition]

print(listings_under100)

             id                                               name    host_id  \
1          3831  Whole flr w/private bdrm, bath & kitchen(pls r...       4869
2          5121                                    BlissArtsSpace!       7356
4          5178                   Large Furnished Room Near B'way　       8967
5          5203                 Cozy Clean Guest Room - Family Apt       7490
8          5803     Lovely Room 1, Garden, Best Area, Legal rental       9744
...         ...                                                ...        ...
46520  44804690    Cozy place, peaceful,  friendly and affordable.  362419479
46523  44807786  Cozy & comfy apt in the heart of Inwood Manhattan  284790520
46524  44811717  Comfortable safe environment 24hr security camera  362453686
46525  44814944                 Upper West Side studio 86th Street    4039777
46526  44818009  5MIN D/N trains, NEAR THE BEACH, 50’ TO MANHATTAN   48098268

         host_name neighbourhood_group       neighbourhood  latitude  \
1      LisaRoxanne            Brooklyn        Clinton Hill  40.68514
2            Garon            Brooklyn  Bedford-Stuyvesant  40.68688
4         Shunichi           Manhattan      Hell's Kitchen  40.76489
5        MaryEllen           Manhattan     Upper West Side  40.80178
8           Laurie            Brooklyn         South Slope  40.66829
...            ...                 ...                 ...       ...
46520         Elia              Queens          St. Albans  40.69980
46523        Salar           Manhattan  Washington Heights  40.85820
46524       Nicole            Brooklyn       East Flatbush  40.65399
46525     Fernando           Manhattan     Upper West Side  40.78731
46526       Marina            Brooklyn           Gravesend  40.59945

       longitude        room_type  price  minimum_nights  number_of_reviews  \
1      -73.95976  Entire home/apt     75               1                340
2      -73.95596     Private room     60              29                 50
4      -73.98493     Private room     65               2                473
5      -73.96723     Private room     75               2                118
8      -73.98779     Private room     88               4                180
...          ...              ...    ...             ...                ...
46520  -73.77104     Private room     44               1                  0
46523  -73.92733  Entire home/apt     87               6                  0
46524  -73.93287     Private room     59               3                  0
46525  -73.97029  Entire home/apt     80              30                  0
46526  -73.98209     Private room     66               1                  0

      last_review  reviews_per_month  calculated_host_listings_count  \
1      2020-08-01               4.75                               1
2      2019-12-02               0.37                               1
4      2020-03-15               3.44                               1
5      2017-07-21               0.89                               1
8      2020-03-18               1.31                               3
...           ...                ...                             ...
46520         NaN                NaN                               1
46523         NaN                NaN                               2
46524         NaN                NaN                               1
46525         NaN                NaN                               1
46526         NaN                NaN                               1

       availability_365
1                   265
2                   365
4                   340
5                     0
8                   344
...                 ...
46520               161
46523                85
46524                90
46525               113
46526                38

[22778 rows x 16 columns]

In [27]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn.
select_condition = data_file["neighbourhood_group"] == "Brooklyn"
df_bk = data_file[select_condition]
print(df_bk)

             id                                               name    host_id  \
1          3831  Whole flr w/private bdrm, bath & kitchen(pls r...       4869
2          5121                                    BlissArtsSpace!       7356
3          5136           Spacious Brooklyn Duplex, Patio + Garden       7378
8          5803     Lovely Room 1, Garden, Best Area, Legal rental       9744
11         6848                   Only 2 stops to Manhattan studio      15991
...         ...                                                ...        ...
46517  44802032                  A very large room in Williamsburg  213793805
46518  44802224  Unique & beautiful design! Skylights-Washer/dryer  143513836
46519  44803201  1200 SF Duplex apt in an old shoe factory/ mon...     921746
46524  44811717  Comfortable safe environment 24hr security camera  362453686
46526  44818009  5MIN D/N trains, NEAR THE BEACH, 50’ TO MANHATTAN   48098268

             host_name neighbourhood_group       neighbourhood  latitude  \
1          LisaRoxanne            Brooklyn        Clinton Hill  40.68514
2                Garon            Brooklyn  Bedford-Stuyvesant  40.68688
3              Rebecca            Brooklyn         Sunset Park  40.66120
8               Laurie            Brooklyn         South Slope  40.66829
11       Allen & Irina            Brooklyn        Williamsburg  40.70837
...                ...                 ...                 ...       ...
46517             Omer            Brooklyn        Williamsburg  40.71970
46518        Elisabeth            Brooklyn       Crown Heights  40.67302
46519  Michael + Josué            Brooklyn        Clinton Hill  40.69034
46524           Nicole            Brooklyn       East Flatbush  40.65399
46526           Marina            Brooklyn           Gravesend  40.59945

       longitude        room_type  price  minimum_nights  number_of_reviews  \
1      -73.95976  Entire home/apt     75               1                340
2      -73.95596     Private room     60              29                 50
3      -73.99423  Entire home/apt    175              14                  1
8      -73.98779     Private room     88               4                180
11     -73.95352  Entire home/apt    109               2                181
...          ...              ...    ...             ...                ...
46517  -73.95632     Private room     55              14                  0
46518  -73.91695     Private room     61              30                  0
46519  -73.96179  Entire home/apt    253              30                  0
46524  -73.93287     Private room     59               3                  0
46526  -73.98209     Private room     66               1                  0

      last_review  reviews_per_month  calculated_host_listings_count  \
1      2020-08-01               4.75                               1
2      2019-12-02               0.37                               1
3      2014-01-02               0.01                               1
8      2020-03-18               1.31                               3
11     2020-03-16               1.32                               1
...           ...                ...                             ...
46517         NaN                NaN                               1
46518         NaN                NaN                               5
46519         NaN                NaN                               1
46524         NaN                NaN                               1
46526         NaN                NaN                               1

       availability_365
1                   265
2                   365
3                   295
8                   344
11                    0
...                 ...
46517                45
46518               363
46519                74
46524                90
46526                38

[18632 rows x 16 columns]

In [28]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.
select_condition = df_bk["price"] < 100
print(df_bk[select_condition])

             id                                               name    host_id  \
1          3831  Whole flr w/private bdrm, bath & kitchen(pls r...       4869
2          5121                                    BlissArtsSpace!       7356
8          5803     Lovely Room 1, Garden, Best Area, Legal rental       9744
21        10452                              Large B&B Style rooms      35935
22        10962            Lovely Room 2; Garden; Best area, Legal       9744
...         ...                                                ...        ...
46510  44798876  Unique & beautiful design! Skylights-Washer/dryer  143513836
46517  44802032                  A very large room in Williamsburg  213793805
46518  44802224  Unique & beautiful design! Skylights-Washer/dryer  143513836
46524  44811717  Comfortable safe environment 24hr security camera  362453686
46526  44818009  5MIN D/N trains, NEAR THE BEACH, 50’ TO MANHATTAN   48098268

         host_name neighbourhood_group       neighbourhood  latitude  \
1      LisaRoxanne            Brooklyn        Clinton Hill  40.68514
2            Garon            Brooklyn  Bedford-Stuyvesant  40.68688
8           Laurie            Brooklyn         South Slope  40.66829
21          Angela            Brooklyn  Bedford-Stuyvesant  40.68310
22          Laurie            Brooklyn         South Slope  40.66869
...            ...                 ...                 ...       ...
46510    Elisabeth            Brooklyn       Crown Heights  40.67156
46517         Omer            Brooklyn        Williamsburg  40.71970
46518    Elisabeth            Brooklyn       Crown Heights  40.67302
46524       Nicole            Brooklyn       East Flatbush  40.65399
46526       Marina            Brooklyn           Gravesend  40.59945

       longitude        room_type  price  minimum_nights  number_of_reviews  \
1      -73.95976  Entire home/apt     75               1                340
2      -73.95596     Private room     60              29                 50
8      -73.98779     Private room     88               4                180
21     -73.95473     Private room     70               3                 75
22     -73.98780     Private room     88               4                180
...          ...              ...    ...             ...                ...
46510  -73.91651     Private room     61              30                  0
46517  -73.95632     Private room     55              14                  0
46518  -73.91695     Private room     61              30                  0
46524  -73.93287     Private room     59               3                  0
46526  -73.98209     Private room     66               1                  0

      last_review  reviews_per_month  calculated_host_listings_count  \
1      2020-08-01               4.75                               1
2      2019-12-02               0.37                               1
8      2020-03-18               1.31                               3
21     2019-10-12               0.60                               2
22     2020-08-03               1.36                               3
...           ...                ...                             ...
46510         NaN                NaN                               5
46517         NaN                NaN                               1
46518         NaN                NaN                               5
46524         NaN                NaN                               1
46526         NaN                NaN                               1

       availability_365
1                   265
2                   365
8                   344
21                  365
22                  365
...                 ...
46510               329
46517                45
46518               363
46524                90
46526                38

[10473 rows x 16 columns]

In [37]:
# 4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.
hosts = ["Michael","David", "John", "Daniel"]
condition = df_bk.host_name.isin(hosts)
df_bk[condition & select_condition]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
201,61747,"Cozy, Brooklyn, Prospect Park Studio",299370,David,Brooklyn,Prospect-Lefferts Gardens,40.65979,-73.96180,Entire home/apt,91,14,97,2018-01-31,0.83,1,44
585,255637,"Prime Prospect Heights, Brooklyn",1343814,Michael,Brooklyn,Prospect Heights,40.67336,-73.96541,Private room,65,31,40,2020-08-08,0.43,1,0
589,257787,Heart of Williamsburg. Brand New.,1356046,Daniel,Brooklyn,Williamsburg,40.71408,-73.94890,Entire home/apt,89,18,272,2020-03-23,2.55,2,104
869,433414,Spacious & Sunny in Prime Brooklyn,287733,David,Brooklyn,Clinton Hill,40.68472,-73.96691,Entire home/apt,99,30,100,2020-07-31,1.01,1,350
1589,841075,Spacious and Clean Brooklyn Flat,4392420,John,Brooklyn,Bushwick,40.70366,-73.92690,Entire home/apt,85,15,22,2016-10-22,0.24,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45372,43956795,Huge studio bedroom w private bathroom + kitchen,352021160,John,Brooklyn,Crown Heights,40.67352,-73.94541,Entire home/apt,47,28,0,NaN,NaN,2,189
45425,43995868,Residency at Bliss Factory's Brooklyn Artist Loft,33373326,Michael,Brooklyn,DUMBO,40.70484,-73.98702,Private room,76,28,0,NaN,NaN,1,365
45618,44114508,2 huge bedrooms + private toilet & kitchen,352021160,John,Brooklyn,Crown Heights,40.67155,-73.94618,Private room,75,28,0,NaN,NaN,2,364
46229,44534901,Sunny Sanctuary Room + Prospect Park/Trains,11308947,Michael,Brooklyn,Prospect-Lefferts Gardens,40.65512,-73.96011,Private room,45,1,0,NaN,NaN,2,359
46326,44609991,"THE ""BUSHWICK EXPERIENCE""- CENTER OF IT ALL!!!",23296177,Daniel,Brooklyn,Bushwick,40.70326,-73.92547,Private room,80,1,0,NaN,NaN,1,90

In [67]:
# 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  
# The prices for all other listings should be the same as the were before. 
condition = df_bk["neighbourhood"] == "Williamsburg"
adj_price = df_bk["price"] * 100
df_bk["adjusted_price"] = np.where(condition, adj_price, 0)

print(df_bk[condition])

             id                                               name    host_id  \
11         6848                   Only 2 stops to Manhattan studio      15991
15         7801                   Sweet and Spacious Brooklyn Loft      21207
35        14290                         * ORIGINAL BROOKLYN LOFT *      56104
38        14377                   Williamsburg 1 bedroom Apartment      56512
42        15385                              Very, very cozy place      60252
...         ...                                                ...        ...
46484  44746041      Modern, light-filled apartment in Wiliamsburg    3317380
46489  44749327  Luxury 3 bedroom apartment Williamsburg ROOF P...  334780877
46493  44753863            Bright, spacious East Williamsburg loft   38062951
46513  44800276        Williamsburg 1 Bedroom, Spacious and Classy  361034257
46517  44802032                  A very large room in Williamsburg  213793805

             host_name neighbourhood_group neighbourhood  latitude  longitude  \
11       Allen & Irina            Brooklyn  Williamsburg  40.70837  -73.95352
15               Chaya            Brooklyn  Williamsburg  40.71842  -73.95718
35               James            Brooklyn  Williamsburg  40.70420  -73.93560
38              Joanna            Brooklyn  Williamsburg  40.70881  -73.95930
42            Cristina            Brooklyn  Williamsburg  40.71185  -73.96204
...                ...                 ...           ...       ...        ...
46484            Marge            Brooklyn  Williamsburg  40.71372  -73.95407
46489    Pedro & Maria            Brooklyn  Williamsburg  40.70902  -73.95610
46493           Nathan            Brooklyn  Williamsburg  40.70372  -73.93492
46513  Angelo + Amirah            Brooklyn  Williamsburg  40.71283  -73.95400
46517             Omer            Brooklyn  Williamsburg  40.71970  -73.95632

             room_type  price  minimum_nights  number_of_reviews last_review  \
11     Entire home/apt    109               2                181  2020-03-16
15     Entire home/apt    299               3                  9  2011-12-28
35     Entire home/apt    131               3                 95  2020-05-28
38     Entire home/apt    175              10                113  2020-01-24
42        Private room     80               7                 49  2020-02-07
...                ...    ...             ...                ...         ...
46484  Entire home/apt    250               7                  0         NaN
46489  Entire home/apt    464               4                  0         NaN
46493  Entire home/apt    100               7                  0         NaN
46513  Entire home/apt    180               7                  0         NaN
46517     Private room     55              14                  0         NaN

       reviews_per_month  calculated_host_listings_count  availability_365  \
11                  1.32                               1                 0
15                  0.07                               1               337
35                  0.73                               1               164
38                  0.87                               1               165
42                  0.39                               1               229
...                  ...                             ...               ...
46484                NaN                               1               164
46489                NaN                               1               344
46493                NaN                               1               146
46513                NaN                               1               364
46517                NaN                               1                45

       adjusted_price
11              10900
15              29900
35              13100
38              17500
42               8000
...               ...
46484           25000
46489           46400
46493           10000
46513           18000
46517            5500

[3486 rows x 17 columns]

/tmp/ipykernel_7752/1501674159.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bk["adjusted_price"] = np.where(condition, adj_price, 0)

In [78]:
# 6. What % of the rooms are private, and what % of the rooms are shared.  

cond_1 = df_bk['room_type'] == "Private room"
private_rooms = len(df_bk[cond_2])/len(df_bk)
non_private = len(df_bk[cond_1])/len(df_bk)
cond_2 = df_bk['room_type'] != "Private room"
print("%.2f" % private_rooms, "% of the rooms are Private")
print(, "% of the rooms are NOT Private")

0.51 % of the rooms are Private
0.49157363675397164 % of the rooms are NOT Private

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [8]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.

In [12]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups.

In [13]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups.

In [14]:
# 4. Using `groupby`, find the mean price for each room type in each neighbourhood_group.

In [15]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.

# Join and file saving.
1. Load the `prices.csv` and the `n_listings.csv`


2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']
       
       
3. Save your joined csv as `joined.csv`


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [16]:
# 1. Load the `prices.csv` and the `n_listings.csv`

In [18]:
# 2. Do join that keeps all the records for each table.

# Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

In [19]:
#  1. Who was won Album of the Year in 2016?

In [20]:
# 2. Who won Best Rap Album in 2009?

In [21]:
# 3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?